import = [
       "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 24

[font.normal]
family = "FiraMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Propo"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono SemBd"
style = "Italic"

[window]
dynamic_padding = true
opacity = 0.8
blur = true
startup_mode = "Maximized"
option_as_alt = "Both"

[window.padding]
x = 20
y = 20